apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp
  labels:
    app: App1
    function: Back-end
spec:
  containers:
    - name: simple-webapp
      image: nginx
      ports:
        - containerPort: 8080